### PR TITLE
Persian--translation

### PR DESCRIPTION
**Pull request by amirftma**

### CODE REVIEW

**Comment by oduvan** [comment]
I accidentally merged this one and only after checking results I figure that you have a wrong name for translation folder.

It should be "fa" instead of "persian"

Can you change it, please?

**Comment by amirftma** [comment]
OK.
fixed :+1:

**Comment by oduvan** [comment]
released  





On Thu, Feb 16, 2017 2:57 PM, amirftma notifications@github.com  wrote:
OK.
fixed 👍

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.



AlexCEO, CheckiO Inc.

CheckiO CheckIO - online game for Python and JavaScript coders checkio.org  

Alexander Lyabah – Medium Read writing from Alexander Lyabah on Medium.
Founder at @PlayCheckiO. Every day, Alexander Lyabah and thousands of other
voices read, write, and share important stories… medium.com  

Follow us

**Comment by amirftma** [comment]
i think there is a problem.
in Persian we  write from right but in English from left.
when i translate mission, in some place i have to use Persian and English together but it make sentence unreadable and change the structure of it !!! 
what can i do to fix it?

**Comment by oduvan** [comment]
I'm not familiar with this kind of problems.

You need to change text align?

**Comment by amirftma** [comment]
i find somethings that might be helpful but i have to learn some HTML.
i don't want to ruin the site, so it will take some time for me to learn HTML.
beside i am so busy and have't much free time.
thanks :smile:

**Comment by oduvan** [comment]
You can share here what you found, maybe I can help.  





On Fri, Feb 17, 2017 6:36 AM, amirftma notifications@github.com  wrote:
i find somethings that might be helpful but i have to learn some HTML.
i don't want to ruin the site, so it will take some time for me to learn HTML.
beside i am so busy and have't much free time.
thanks 😄

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.



AlexCEO, CheckiO Inc.

CheckiO CheckIO - online game for Python and JavaScript coders checkio.org  

Alexander Lyabah – Medium Read writing from Alexander Lyabah on Medium.
Founder at @PlayCheckiO. Every day, Alexander Lyabah and thousands of other
voices read, write, and share important stories… medium.com  

Follow us

**Pull request merged**
